name: Bisect randon failures

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:11.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      RUBYOPT: '-W:no-deprecated -W:no-experimental'
      JAVASCRIPT_DRIVER: headless_chrome
      DB_HOST: localhost
      DB_NAME_TEST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      CAPYBARA_MAX_WAIT_TIME: 5
      SPEC_USER_TIME_ZONE: Etc/UTC
      SPEC_RETRY_COUNT: 2
      ALLOW_EMAIL_SIGN_IN: true

    steps:
      - name: Build Start Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: lms
          SLACK_ICON_EMOJI: growthtribe
          SLACK_TITLE: Bisect STARTED
          SLACK_COLOR: '#dbab0a'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: ref,actions url,commit
      - uses: actions/checkout@v2
      - name: Use Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: |
          bundle exec rake db:schema:load
      - name: Precompile Assets
        run: |
          bundle exec rails assets:precompile
          echo Precompilation complete. Cleaning assets...
          bundle exec rails assets:clean
          echo Cleaning complete! All done.
      - name: Specs
        run: bundle exec rspec --order random --seed 16687 --bisect
      - name: Build Finished Slack Notification
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: lms
          SLACK_ICON_EMOJI: growthtribe
          SLACK_TITLE: ${{ job.status == 'success' && 'Bisect COMPLETED' || job.status == 'cancelled' && 'Bisect CANCELLED' || 'Bisect FAILED' }}
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || job.status == 'cancelled' && '#808080' || 'danger' }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: ref,actions url,commit
